// ============================================================
// KMeans parity / determinism test (mirror of tests/agentParity.test.mjs,
// tests/logregParity.test.mjs and tests/knnParity.test.mjs).
//
// The trainer twin lives in scripts/train_kmeans.py (stdlib Python) and
// ships data/agent/kmeans-pca-{en,fr,ar}.json after running it, so this
// test is SELF-CONTAINED:
//   - builds a deterministic fixture on-device with createKmeans +
//     addMemoryKmeans + sealKmeans (same API trust boundary as knn.js),
//   - asserts the math spec is locked (KMEANS_MATH_SPEC: q=16, k=8,
//     cosine-unit-tfidf features, euclidean distance, power-iteration PCA,
//     farthest-point seeding, strict-less nearest index),
//   - asserts predictKmeans returns {clusterId, edge, centroid, projection}
//     with sane shapes (projection/centroid lengths = q),
//   - asserts determinism (two identical calls -> identical projection),
//   - asserts serialize -> deserialize round-trips to 1e-9.
//
// If data/agent/kmeans-pca-{en,fr,ar}.json are present (generated by the
// Python twin), it verifies REAL parity to 1e-6: for each shipped probe
// (which embeds its EXACT token list) JS predictKmeans is replayed on those
// same tokens and clusterId/edge/centroid/projection are compared 1-by-1 to
// the Python-shipped reference. True JS<->Python parity, not a range check.
// ============================================================

import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  KMEANS_MATH_SPEC,
  createKmeans,
  addMemoryKmeans,
  sealKmeans,
  predictKmeans,
  serializeKmeans,
  deserializeKmeans,
} from '../js/agent/kmeans.js';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const load = (name) => JSON.parse(readFileSync(join(root, name), 'utf8'));

const EPS = 1e-6;

function buildFixture() {
  const m = createKmeans();
  addMemoryKmeans(m, 'greeting', ['hello', 'hi', 'hey', 'good', 'morning']);
  addMemoryKmeans(m, 'farewell', ['goodbye', 'bye', 'see', 'you', 'later']);
  addMemoryKmeans(m, 'thanks', ['thanks', 'thank', 'you', 'much']);
  addMemoryKmeans(m, 'time', ['what', 'time', 'is', 'it', 'clock']);
  addMemoryKmeans(m, 'lights', ['turn', 'off', 'the', 'lights', 'switch']);
  addMemoryKmeans(m, 'weather', ['weather', 'rain', 'sun', 'cold', 'hot']);
  addMemoryKmeans(m, 'morning', ['good', 'morning', 'wake', 'day']);
  addMemoryKmeans(m, 'night', ['good', 'night', 'sleep', 'bed']);
  addMemoryKmeans(m, 'music', ['play', 'song', 'music', 'volume', 'stop']);
  return sealKmeans(m);
}

describe('M10-kmeans: math spec + determinism', () => {
  it('math spec is locked', () => {
    expect(KMEANS_MATH_SPEC.schema).toBe(1);
    expect(KMEANS_MATH_SPEC.algorithm).toBe('kmeans-pca-1');
    expect(KMEANS_MATH_SPEC.q).toBe(16);
    expect(KMEANS_MATH_SPEC.k).toBe(8);
    expect(KMEANS_MATH_SPEC.metric).toBe('cosine-unit-tfidf');
    expect(KMEANS_MATH_SPEC.distance).toBe('euclidean');
    expect(KMEANS_MATH_SPEC.pca).toBe('mean-centered-power-iteration-deflation');
    expect(KMEANS_MATH_SPEC.seeds).toBe('farthest-point-index-asc');
    expect(KMEANS_MATH_SPEC.lloyd).toBe('strict-less-nearest-index');
  });

  it('seal is idempotent and vocabulary is lexicographically sorted', () => {
    const m = buildFixture();
    const vocab = [...m.vocabulary];
    expect(vocab).toEqual([...vocab].sort());
    const before = [...vocab];
    sealKmeans(m);
    expect([...m.vocabulary]).toEqual(before);
    expect(m.sealed).toBe(true);
  });

  it('predict is deterministic (same input -> same projection, twice)', () => {
    const m = buildFixture();
    const a = predictKmeans(m, ['good', 'morning', 'wake']);
    const b = predictKmeans(m, ['good', 'morning', 'wake']);
    expect(a.projection).toEqual(b.projection);
    expect(a.centroid).toEqual(b.centroid);
    expect(a.clusterId).toBe(b.clusterId);
    expect(a.edge).toBe(b.edge);
  });

  it('unknown tokens are skipped (contribute 0) per spec', () => {
    const m = buildFixture();
    const known = predictKmeans(m, ['hello']);
    const withUnknown = predictKmeans(m, ['hello', 'zzzzqqq']);
    expect(withUnknown.projection).toEqual(known.projection); // unknown skipped
    expect(withUnknown.clusterId).toBe(known.clusterId);
  });

  it('predict returns q-dim shape + sane ranges', () => {
    const m = buildFixture();
    const r = predictKmeans(m, ['hello', 'there']);
    expect(typeof r.clusterId).toBe('number');
    expect(typeof r.edge).toBe('number');
    expect(Array.isArray(r.centroid)).toBe(true);
    expect(Array.isArray(r.projection)).toBe(true);
    expect(r.projection.length).toBe(m.q);
    expect(r.centroid.length).toBe(m.q);
    expect(r.edge).toBeGreaterThanOrEqual(0);
    expect(r.clusterId).toBeGreaterThanOrEqual(0);
    expect(r.clusterId).toBeLessThan(m.k);
  });

  it('empty query is stable and safe', () => {
    const m = buildFixture();
    const a = predictKmeans(m, []);
    const b = predictKmeans(m, []);
    expect(a.projection).toEqual(b.projection);
    expect(a.clusterId).toBe(b.clusterId);
  });

  it('serialize/deserialize round-trips to 1e-12', () => {
    const m = buildFixture();
    const data = serializeKmeans(m);
    const back = deserializeKmeans(data);
    expect(back.schema).toBe(m.schema);
    expect(back.algorithm).toBe(m.algorithm);
    expect(back.classes).toEqual(m.classes);
    expect(back.vocabulary).toEqual(m.vocabulary);
    expect(back.assignments).toEqual(m.assignments);
    for (let i = 0; i < m.mean.length; i++) {
      expect(Math.abs((data.mean[i] || 0) - (m.mean[i] || 0))).toBeLessThan(1e-12);
    }
    for (let c = 0; c < m.centroids.length; c++) {
      for (let j = 0; j < m.q; j++) {
        expect(Math.abs((data.centroids[c][j] || 0) - (m.centroids[c][j] || 0))).toBeLessThan(1e-12);
      }
    }
  });
});

describe('kmeans: shipped-memory parity to 1e-6 (mirror of logreg/knn, skipped when absent)', () => {
  for (const lang of ['en', 'fr', 'ar']) {
    const p = join(root, `data/agent/kmeans-pca-${lang}.json`);
    if (!existsSync(p)) {
      it.skip(`${lang}: kmeans-pca-${lang}.json not shipped yet (run scripts/train_kmeans.py)`);
      continue;
    }
    it(`${lang}: JS predictKmeans replays shipped Python probes to 1e-6`, () => {
      const data = load(`data/agent/kmeans-pca-${lang}.json`);
      const m = deserializeKmeans(data);
      expect(m.schema).toBe(data.schema);
      expect(m.algorithm).toBe(data.algorithm);
      expect(m.q).toBe(data.q);
      expect(m.k).toBe(data.k);
      expect(m.centroids).toHaveLength(data.k);
      for (const probe of data.probes || []) {
        const r = predictKmeans(m, probe.tokens || []);
        expect(r.clusterId, JSON.stringify(probe.tokens)).toBe(probe.clusterId);
        expect(Math.abs(r.edge - probe.edge), `edge ${probe.clusterId}`).toBeLessThan(EPS);
        expect(r.projection).toHaveLength(probe.projection.length);
        expect(r.centroid).toHaveLength(probe.centroid.length);
        for (let i = 0; i < probe.projection.length; i++) {
          expect(Math.abs(r.projection[i] - probe.projection[i]), `proj[${i}]`).toBeLessThan(EPS);
        }
        for (let i = 0; i < probe.centroid.length; i++) {
          expect(Math.abs(r.centroid[i] - probe.centroid[i]), `cent[${i}]`).toBeLessThan(EPS);
        }
      }
    });
  }
});