// ============================================================
// KNN parity / determinism test (mirror of tests/agentParity.test.mjs and
// tests/logregParity.test.mjs).
//
// The trainer twin lives in scripts/train_knn.py (stdlib Python) and ships
// knn-memory-{en,fr,ar}.json after running it, so this test is SELF-CONTAINED:
//   - builds a deterministic fixture on-device with createKnn + addMemoryKnn
//     + sealKnn (same API trust boundary as nb.js/logreg.js),
//   - asserts the math spec is locked (KNN_MATH_SPEC: cosine, k=3,
//     idf=log(nDocs/df), unknown tokens skipped),
//   - asserts predictKnn returns the SAME contract shape as predictNb /
//     predictLogReg ({scores, probs, id, confidence, margin}),
//   - asserts determinism (two identical calls -> identical scores/probs),
//   - asserts serialize -> deserialize round-trips to 1e-9.
//
// If data/agent/knn-memory-{en,fr,ar}.json are present (generated by the
// Python twin), it verifies REAL parity to 1e-6: for each shipped probe
// (which embeds its EXACT token list) JS predictKnn is replayed on those
// same tokens and id/confidence/margin/scores/probs are compared 1-by-1 to
// the Python-shipped reference. True JS<->Python parity, not a range check.
// ============================================================

import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  KNN_MATH_SPEC,
  createKnn,
  addMemoryKnn,
  sealKnn,
  predictKnn,
  serializeKnn,
  deserializeKnn,
} from '../js/agent/knn.js';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const load = (name) => JSON.parse(readFileSync(join(root, name), 'utf8'));

const EPS = 1e-6;

function buildFixture() {
  const m = createKnn();
  addMemoryKnn(m, 'greeting', ['hello', 'hi', 'hey', 'good', 'morning']);
  addMemoryKnn(m, 'farewell', ['goodbye', 'bye', 'see', 'you', 'later']);
  addMemoryKnn(m, 'thanks', ['thanks', 'thank', 'you', 'much']);
  return sealKnn(m);
}

describe('M9-knn: math spec + determinism', () => {
  it('math spec is locked', () => {
    expect(KNN_MATH_SPEC.schema).toBe(1);
    expect(KNN_MATH_SPEC.algorithm).toBe('knn-cosine-1');
    expect(KNN_MATH_SPEC.metric).toBe('cosine');
    expect(KNN_MATH_SPEC.k).toBe(3);
    expect(KNN_MATH_SPEC.idf).toBe('log(nDocs/df)');
    expect(KNN_MATH_SPEC.log).toBe('natural');
  });

  it('seal is idempotent and vocabulary is lexicographically sorted', () => {
    const m = sealKnn(buildFixture());
    const vocab = [...m.vocabulary];
    expect(vocab).toEqual([...vocab].sort());
    const before = [...vocab];
    sealKnn(m);
    expect([...m.vocabulary]).toEqual(before);
  });

  it('predict is deterministic (same input -> same output, twice)', () => {
    const m = buildFixture();
    const a = predictKnn(m, ['hello', 'good', 'morning']);
    const b = predictKnn(m, ['hello', 'good', 'morning']);
    expect(a.scores).toEqual(b.scores);
    expect(a.probs).toEqual(b.probs);
    expect(a.id).toBe(b.id);
    expect(a.confidence).toBeCloseTo(b.confidence, 9);
    expect(a.margin).toBeCloseTo(b.margin, 9);
  });

  it('unknown tokens are skipped (contribute 0) per spec', () => {
    const m = buildFixture();
    const known = predictKnn(m, ['hello']);
    const withUnknown = predictKnn(m, ['hello', 'zzzzqqq']);
    expect(withUnknown.scores).toEqual(known.scores); // unknown skipped
    expect(withUnknown.id).toBe(known.id);
  });

  it('predict returns the predictNb contract shape + sane ranges', () => {
    const m = buildFixture();
    const r = predictKnn(m, ['hello', 'there']);
    expect(typeof r.id).toBe('string');
    expect(typeof r.confidence).toBe('number');
    expect(typeof r.margin).toBe('number');
    expect(Array.isArray(r.scores)).toBe(true);
    expect(Array.isArray(r.probs)).toBe(true);
    expect(r.scores.length).toBe(m.classes.length);
    expect(r.probs.length).toBe(m.classes.length);
    expect(r.confidence).toBeGreaterThan(0);
    expect(r.confidence).toBeLessThanOrEqual(1);
    expect(r.margin).toBeGreaterThanOrEqual(0);
  });

  it('empty query falls back to a safe empty contract', () => {
    const m = buildFixture();
    const r = predictKnn(m, []);
    expect(typeof r.id).toBe('string');
    expect(r.scores.length).toBe(m.classes.length);
    expect(r.probs.length).toBe(m.classes.length);
  });

  it('serialize/deserialize round-trips to 1e-9', () => {
    const m = buildFixture();
    const data = serializeKnn(m);
    const back = deserializeKnn(data);
    expect(back.schema).toBe(m.schema);
    expect(back.algorithm).toBe(m.algorithm);
    expect(back.classes).toEqual(m.classes);
    expect(back.vocabulary).toEqual(m.vocabulary);
    expect(back.nDocs).toBe(m.nDocs);
    for (const t of m.vocabulary) {
      expect(Math.abs((data.idf[t] || 0) - (m.idf.get(t) || 0))).toBeLessThan(1e-12);
    }
  });
});

describe('knn: shipped-memory parity to 1e-6 (mirror of logreg, skipped when absent)', () => {
  for (const lang of ['en', 'fr', 'ar']) {
    const p = join(root, `data/agent/knn-memory-${lang}.json`);
    if (!existsSync(p)) {
      it.skip(`${lang}: knn-memory-${lang}.json not shipped yet (run scripts/train_knn.py)`);
      continue;
    }
    it(`${lang}: JS predictKnn replays shipped Python probes score-by-score to 1e-6`, () => {
      const data = load(`data/agent/knn-memory-${lang}.json`);
      const m = deserializeKnn(data);
      expect(m.schema).toBe(data.schema);
      expect(m.algorithm).toBe(data.algorithm);
      expect(m.classes).toEqual(data.classes);
      expect(m.vocabulary).toEqual([...data.vocabulary].sort());
      for (const probe of data.probes || []) {
        const r = predictKnn(m, probe.tokens || []);
        expect(r.id, JSON.stringify(probe.tokens)).toBe(probe.id);
        expect(Math.abs(r.confidence - probe.confidence), `conf ${probe.id}`).toBeLessThan(EPS);
        expect(Math.abs(r.margin - probe.margin), `margin ${probe.id}`).toBeLessThan(EPS);
        expect(r.scores).toHaveLength(probe.scores.length);
        for (let i = 0; i < probe.scores.length; i++) {
          expect(Math.abs(r.scores[i] - probe.scores[i]), `score[${i}]`).toBeLessThan(EPS);
          expect(Math.abs(r.probs[i] - probe.probs[i]), `probs[${i}]`).toBeLessThan(EPS);
        }
      }
    });
  }
});