// ============================================================
// LogReg parity / determinism test (mirror of tests/agentParity.test.mjs).
//
// Because the trainer twin lives in scripts/train_logreg.py (stdlib Python)
// and its shipped weights ARE guaranteed to be present after running that
// script, this test is SELF-CONTAINED:
//   - it builds a deterministic fixture on-device with createLogReg +
//     partialFitLogReg (same API trust boundary as nb.js),
//   - asserts the math spec is locked (LOGREG_MATH_SPEC),
//   - asserts predictLogReg returns the SAME contract shape as predictNb
//     ({scores, probs, id, confidence, margin}),
//   - asserts determinism (two identical calls -> identical scores/probs),
//   - asserts unknown-token skip (unknown tokens are SKIPPED per spec),
//   - asserts confidence/margin stay in (0,1],
//   - asserts serialize -> deserialize round-trips to 1e-9 (byte-safe,
//     matching agentParity's closure approach).
//
// If data/agent/logreg-weights-{en,fr,ar}.json are present (generated by
// the Python twin), it additionally verifies REAL parity to 1e-6: for each
// shipped probe (which embeds its exact token list) JS predictLogReg is
// replayed on those same tokens and the returned id/confidence/margin/
// scores/probs are compared 1-by-1 to the Python-shipped reference. That is
// a true JS<->Python parity, not a range check.
// ============================================================

import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  LOGREG_MATH_SPEC,
  createLogReg,
  partialFitLogReg,
  sealLogReg,
  predictLogReg,
  serializeLogReg,
  deserializeLogReg,
} from '../js/agent/logreg.js';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const load = (name) => JSON.parse(readFileSync(join(root, name), 'utf8'));

const EPS = 1e-6;

function buildFixture() {
  const m = createLogReg();
  partialFitLogReg(m, 'greeting', ['hello', 'hi', 'hey', 'good', 'morning'], 1);
  partialFitLogReg(m, 'farewell', ['goodbye', 'bye', 'see', 'you', 'later'], 1);
  partialFitLogReg(m, 'thanks', ['thanks', 'thank', 'you', 'much'], 0.5);
  sealLogReg(m);
  return m;
}

describe('M8-logreg: math spec + determinism', () => {
  it('math spec is locked', () => {
    expect(LOGREG_MATH_SPEC.schema).toBe(1);
    expect(LOGREG_MATH_SPEC.algorithm).toBe('multinomial-logreg-1');
    expect(LOGREG_MATH_SPEC.epochs).toBe(200);
    expect(LOGREG_MATH_SPEC.lr).toBe(0.05);
    expect(LOGREG_MATH_SPEC.l2).toBe(1e-4);
    expect(LOGREG_MATH_SPEC.logBase).toBe('natural');
    expect(LOGREG_MATH_SPEC.unknownToken).toBe('skip');
    expect(LOGREG_MATH_SPEC.tieBreak).toBe('score-desc-class-idx-asc');
    expect(LOGREG_MATH_SPEC.init).toBe('zeros');
    expect(LOGREG_MATH_SPEC.features).toBe('bag-of-words-normalized');
  });

  it('seal is idempotent and vocabulary is lexicographically sorted', () => {
    const m = sealLogReg(buildFixture());
    const vocab = [...m.vocab.keys()];
    expect(vocab).toEqual([...vocab].sort());
    // second seal is a no-op but must not throw / mutate
    const before = [...vocab];
    sealLogReg(m);
    expect(m.vocab.keys().toArray ? [...m.vocab.keys()] : [...m.vocab.keys()]).toEqual(before);
  });

  it('predict is deterministic (same input -> same output, twice)', () => {
    const m = sealLogReg(buildFixture());
    const a = predictLogReg(m, ['hello', 'good', 'morning']);
    const b = predictLogReg(m, ['hello', 'good', 'morning']);
    expect(a.scores).toEqual(b.scores);
    expect(a.probs).toEqual(b.probs);
    expect(a.id).toBe(b.id);
    expect(a.confidence).toBeCloseTo(b.confidence, 9);
    expect(a.margin).toBeCloseTo(b.margin, 9);
  });

  it('unknown tokens are skipped (contribute 0) per spec', () => {
    const m = sealLogReg(buildFixture());
    const known = predictLogReg(m, ['hello']);
    const withUnknown = predictLogReg(m, ['hello', 'zzzzqqq']);
    expect(withUnknown.scores).toEqual(known.scores); // unknown skipped
    expect(withUnknown.id).toBe(known.id);
  });

  it('predict returns the predictNb contract shape + sane ranges', () => {
    const m = sealLogReg(buildFixture());
    const r = predictLogReg(m, ['hello', 'there']);
    expect(typeof r.id).toBe('string');
    expect(typeof r.confidence).toBe('number');
    expect(typeof r.margin).toBe('number');
    expect(Array.isArray(r.scores)).toBe(true);
    expect(Array.isArray(r.probs)).toBe(true);
    expect(r.scores.length).toBe(m.classes.length);
    expect(r.probs.length).toBe(m.classes.length);
    expect(r.confidence).toBeGreaterThan(0);
    expect(r.confidence).toBeLessThanOrEqual(1);
    expect(r.margin).toBeGreaterThanOrEqual(0);
  });

  it('tie-break: (score desc, class idx asc)', () => {
    const m = sealLogReg(buildFixture());
    // empty doc -> all scores equal 0 -> insertion order wins
    const r = predictLogReg(m, []);
    expect(r.id).toBe('greeting'); // first class inserted
  });

  it('serialize/deserialize round-trips to 1e-9', () => {
    const m = sealLogReg(buildFixture());
    const data = serializeLogReg(m);
    const back = deserializeLogReg(data);
    expect(back.schema).toBe(m.schema);
    expect(back.algorithm).toBe(m.algorithm);
    expect(back.classes).toEqual(m.classes);
    expect([...back.vocab.keys()]).toEqual([...m.vocab.keys()].sort());
    for (const c of m.classes) {
      const jsW = serializeLogReg(sealLogReg(buildFixture())).weights[c];
      const backW = data.weights[c];
      for (const t of Object.keys(backW)) {
        expect(Math.abs((jsW[t] || 0) - (backW[t] || 0))).toBeLessThan(1e-9);
      }
    }
  });
});

describe('logreg: shipped-weight parity to 1e-6 (mirror of agentParity, skipped when absent)', () => {
  for (const lang of ['en', 'fr', 'ar']) {
    const p = join(root, `data/agent/logreg-weights-${lang}.json`);
    if (!existsSync(p)) {
      it.skip(`${lang}: logreg-weights-${lang}.json not shipped yet (run scripts/train_logreg.py)`);
      continue;
    }
    it(`${lang}: JS predictLogReg replays shipped Python probes score-by-score to 1e-6`, () => {
      const data = load(`data/agent/logreg-weights-${lang}.json`);
      const m = deserializeLogReg(data);
      expect(m.schema).toBe(data.schema);
      expect(m.algorithm).toBe(data.algorithm);
      expect(m.classes).toEqual(data.classes);
      expect([...m.vocab.keys()]).toEqual([...data.vocabulary].sort());
      for (const probe of data.probes || []) {
        const r = predictLogReg(m, probe.tokens || []);
        expect(r.id, JSON.stringify(probe.tokens)).toBe(probe.id);
        expect(Math.abs(r.confidence - probe.confidence), `conf ${probe.id}`).toBeLessThan(EPS);
        expect(Math.abs(r.margin - probe.margin), `margin ${probe.id}`).toBeLessThan(EPS);
        expect(r.scores).toHaveLength(probe.scores.length);
        for (let i = 0; i < probe.scores.length; i++) {
          expect(Math.abs(r.scores[i] - probe.scores[i]), `score[${i}]`).toBeLessThan(EPS);
          expect(Math.abs(r.probs[i] - probe.probs[i]), `probs[${i}]`).toBeLessThan(EPS);
        }
      }
    });
  }
});
